Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2020-12, with the labels that each got.

#2446 fix(patients): patient view buttons hover style inconsistency
  src/patients/view/ImportantPatientInfo.tsx
Labels: hacktoberfest-accepted, patients, 🐛bug

#2479 feat(lab): link visit to labs
  src/__tests__/labs/requests/NewLabRequest.test.tsx
  src/labs/requests/NewLabRequest.tsx
  src/shared/model/Lab.ts
Labels: in progress

#2525 feat: update button text to align with domain
  src/__tests__/imagings/requests/NewImagingRequest.test.tsx
  src/__tests__/labs/ViewLab.test.tsx
  src/__tests__/labs/requests/NewLabRequest.test.tsx
  src/__tests__/medications/ViewMedication.test.tsx
  src/__tests__/medications/requests/NewMedicationRequest.test.tsx
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/new/NewPatient.test.tsx
  src/__tests__/scheduling/appointments/edit/EditAppointment.test.tsx
  src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
  src/imagings/requests/NewImagingRequest.tsx
  src/incidents/report/ReportIncident.tsx
  src/labs/ViewLab.tsx
  src/labs/requests/NewLabRequest.tsx
  src/medications/ViewMedication.tsx
  src/medications/requests/NewMedicationRequest.tsx
  src/patients/edit/EditPatient.tsx
  src/patients/new/NewPatient.tsx
  src/scheduling/appointments/edit/EditAppointment.tsx
  src/scheduling/appointments/new/NewAppointment.tsx
  src/shared/locales/enUs/translations/imagings/index.ts
  src/shared/locales/enUs/translations/labs/index.ts
  src/shared/locales/enUs/translations/medications/index.ts
  src/shared/locales/enUs/translations/patients/index.ts
  src/shared/locales/enUs/translations/scheduling/index.ts
Labels: in progress

#2526 Changing import statements to reduce bundle size
  package.json
  src/__tests__/incidents/hooks/useReportIncident.test.tsx
  src/__tests__/incidents/hooks/useResolvedIncident.test.tsx
  src/__tests__/incidents/util/validate-incident.test.ts
  src/__tests__/patients/GeneralInformation.test.tsx
  src/__tests__/patients/care-goals/CareGoalForm.test.tsx
  src/__tests__/patients/care-plans/CarePlanForm.test.tsx
  src/__tests__/patients/diagnoses/DiagnosisForm.test.tsx
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/patient-slice.test.ts
  src/__tests__/patients/util/validate-caregoal.test.ts
  src/__tests__/patients/util/validate-careplan.test.ts
  src/__tests__/patients/util/validate-patient.test.ts
  src/__tests__/patients/util/validate-visit.test.ts
  src/__tests__/patients/visits/VisitForm.test.tsx
  src/__tests__/scheduling/appointments/AppointmentDetailForm.test.tsx
  src/__tests__/scheduling/appointments/edit/EditAppointment.test.tsx
  src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
  src/__tests__/shared/db/PatientRepository.test.ts
  src/incidents/util/validate-incident.ts
  src/patients/GeneralInformation.tsx
  src/patients/care-goals/AddCareGoalModal.tsx
  src/patients/care-goals/CareGoalTable.tsx
  src/patients/care-plans/AddCarePlanModal.tsx
  src/patients/util/timestamp-id-generator.ts
  src/patients/util/validate-caregoal.ts
  src/patients/util/validate-careplan.ts
  src/patients/util/validate-patient.ts
  src/patients/util/validate-visit.ts
  src/patients/visits/AddVisitModal.tsx
  src/scheduling/appointments/edit/EditAppointment.tsx
  src/scheduling/appointments/new/NewAppointment.tsx
  src/scheduling/appointments/util/validate-appointment.ts
Labels: in progress

#2536 fix: button labels and status labels
  src/patients/care-goals/CareGoalTable.tsx
  src/shared/locales/enUs/translations/incidents/index.ts
Labels: incidents, 🐛bug
