Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2020-06, with the labels that each got.

#2028 [i18n] add edit patient for all languages
  src/locales/ar/translations/patients/index.ts
  src/locales/de/translations/patients/index.ts
  src/locales/es/translations/patients/index.ts
  src/locales/fr/translations/patients/index.ts
  src/locales/id/translations/patients/index.ts
  src/locales/ja/translations/patients/index.ts
  src/locales/ptBr/translations/patients/index.ts
  src/locales/ru/translations/patients/index.ts
  src/locales/zhCN/translations/patients/index.ts
Labels: in progress, patients, 🚀enhancement

#2111 feat(incident): Added Report Incident button
  src/incidents/list/ViewIncidents.tsx
Labels: incidents, 🚀enhancement

#2115 feat(care plan): Add care plans to patients
  src/__tests__/patients/care-plans/AddCarePlanModal.test.tsx
  src/__tests__/patients/care-plans/CarePlanForm.test.tsx
  src/__tests__/patients/care-plans/CarePlanTab.test.tsx
  src/__tests__/patients/care-plans/CarePlanTable.test.tsx
  src/__tests__/patients/care-plans/ViewCarePlan.test.tsx
  src/__tests__/patients/patient-slice.test.ts
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/components/input/SelectWithLableFormGroup.tsx
  src/locales/enUs/translations/patient/index.ts
  src/model/CarePlan.ts
  src/model/Patient.ts
  src/model/Permissions.ts
  src/patients/care-plans/AddCarePlanModal.tsx
  src/patients/care-plans/CarePlanForm.tsx
  src/patients/care-plans/CarePlanTab.tsx
  src/patients/care-plans/CarePlanTable.tsx
  src/patients/care-plans/ViewCarePlan.tsx
  src/patients/patient-slice.ts
  src/patients/view/ViewPatient.tsx
  src/user/user-slice.ts
Labels: patients, 🚀enhancement

#2109 feat(network-status): Notify users when they're working offline
  src/HospitalRun.tsx
  src/__tests__/components/network-status/NetworkStatusMessage.test.tsx
  src/components/network-status/NetworkStatusMessage.tsx
  src/components/network-status/index.ts
  src/components/network-status/types.ts
  src/components/network-status/useNetworkStatus.ts
  src/locales/enUs/translations/index.ts
  src/locales/enUs/translations/network-status/index.ts
Labels: in progress

#2112 fix(sidebar): sidebar should only show links user has access to see
  src/__tests__/components/Sidebar.test.tsx
  src/components/Sidebar.tsx
Labels: in progress

#2026 feat(patient): add paging and sorting functionality
  src/__tests__/clients/db/PatientRepository.test.ts
  src/__tests__/components/PageComponent.test.tsx
  src/__tests__/hooks/useUpdateEffect.test.ts
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/list/ViewPatients.test.tsx
  src/__tests__/patients/patients-slice.test.ts
  src/clients/Page.ts
  src/clients/db/PageRequest.ts
  src/clients/db/PatientRepository.ts
  src/clients/db/Repository.ts
  src/components/PageComponent.tsx
  src/hooks/useUpdateEffect.ts
  src/locales/enUs/translations/actions/index.ts
  src/model/Patient.ts
  src/patients/edit/EditPatient.tsx
  src/patients/list/ViewPatients.tsx
  src/patients/patients-slice.ts
Labels: help wanted, in progress, patients

#2118 fix(navbar): Make Navbar mobile-friendly
  src/__tests__/components/Navbar.test.tsx
  src/components/Navbar.tsx
  src/pageMap.tsx
  src/user/user-slice.ts
Labels: in progress

#2034 feat(i18n): add new script for checking missing translations
  .eslintrc.js
  .gitignore
  package.json
  scripts/.eslintrc.js
  scripts/checkMissingTranslations.ts
  scripts/tsconfig.json
  src/i18n.ts
  src/locales/index.ts
Labels: in progress, localization, 🚀enhancement

#2131 ci(node): add node 14 on windows and mac
  .github/workflows/ci.yml
Labels: ci/cd, core-team

#2113 feat(patient): multiple contact info
  src/__tests__/patients/ContactInfo.test.tsx
  src/__tests__/patients/GeneralInformation.test.tsx
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/new/NewPatient.test.tsx
  src/__tests__/patients/patient-slice.test.ts
  src/components/input/SelectWithLableFormGroup.tsx
  src/components/input/TextFieldWithLabelFormGroup.tsx
  src/components/input/TextInputWithLabelFormGroup.tsx
  src/locales/enUs/translations/actions/index.ts
  src/locales/enUs/translations/patient/index.ts
  src/model/ContactInformation.ts
  src/patients/ContactInfo.tsx
  src/patients/ContactInfoTypes.ts
  src/patients/GeneralInformation.tsx
  src/patients/edit/EditPatient.tsx
  src/patients/new/NewPatient.tsx
  src/patients/patient-slice.ts
  src/patients/util/set-patient-helper.ts
Labels: in progress

#2158 fix(patient): make note not required in care plan
  src/__tests__/patients/care-plans/AddCarePlanModal.test.tsx
  src/__tests__/patients/care-plans/CarePlanForm.test.tsx
  src/__tests__/patients/patient-slice.test.ts
  src/patients/care-plans/CarePlanForm.tsx
  src/patients/patient-slice.ts
Labels: patients, 🚀enhancement

#2171 Components update to 1.14.2
  package.json
  src/__tests__/components/Navbar.test.tsx
  src/__tests__/components/PageComponent.test.tsx
  src/__tests__/components/input/SelectWithLabelFormGroup.test.tsx
  src/__tests__/incidents/list/ViewIncidents.test.tsx
  src/__tests__/patients/ContactInfo.test.tsx
  src/__tests__/patients/GeneralInformation.test.tsx
  src/__tests__/patients/care-plans/CarePlanForm.test.tsx
  src/__tests__/scheduling/appointments/AppointmentDetailForm.test.tsx
  src/components/Navbar.tsx
  src/components/PageComponent.tsx
  src/components/input/LanguageSelector.tsx
  src/components/input/SelectWithLableFormGroup.tsx
  src/incidents/list/ViewIncidents.tsx
  src/labs/ViewLabs.tsx
  src/patients/ContactInfo.tsx
  src/patients/GeneralInformation.tsx
  src/patients/care-plans/CarePlanForm.tsx
  src/scheduling/appointments/AppointmentDetailForm.tsx
Labels: critical, in progress

#2173 chore(lint): turn off @typescript-eslint/explicit-module-boundary-types
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ci/cd

#2178 fix(patient): add DOB to add related person search
  src/patients/related-persons/AddRelatedPersonModal.tsx
Labels: patients, 🚀enhancement

#2189 refactor: use Table component
  .eslintrc.js
  src/__tests__/incidents/list/ViewIncidents.test.tsx
  src/__tests__/labs/ViewLabs.test.tsx
  src/__tests__/patients/care-plans/CarePlanTable.test.tsx
  src/__tests__/patients/labs/LabsTab.test.tsx
  src/__tests__/patients/list/ViewPatients.test.tsx
  src/__tests__/patients/related-persons/RelatedPersonsTab.test.tsx
  src/incidents/list/ViewIncidents.tsx
  src/labs/ViewLabs.tsx
  src/patients/care-plans/CarePlanTable.tsx
  src/patients/labs/LabsTab.tsx
  src/patients/list/ViewPatients.tsx
  src/patients/related-persons/RelatedPersonTab.tsx
  src/shared/components/input/TextFieldWithLabelFormGroup.tsx
  src/shared/db/IncidentRepository.ts
  src/shared/db/Repository.ts
  src/shared/locales/enUs/translations/actions/index.ts
Labels: labs, 🐛bug, 🚀enhancement

#2193 docs: add note about making hospitalrun a public database
  .github/CONTRIBUTING.md
Labels: docs
