Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2020-10, with the labels that each got.

#2423 fix(lab request): Update Toast success message
  src/labs/requests/NewLabRequest.tsx
  src/shared/locales/enUs/translations/labs/index.ts
Labels: hacktoberfest-accepted, in progress

#2333 feat(patient): add panel to display useful patient information
  src/__tests__/patients/view/ImportantPatientInfo.test.tsx
  src/patients/view/ImportantPatientInfo.tsx
  src/patients/view/ViewPatient.tsx
  src/shared/locales/enUs/translations/patient/index.ts
Labels: hacktoberfest-accepted, in progress, patients, 🚀enhancement

#2424 refactor(scheduling): use react hooks and react query, phase out redux
  src/__tests__/scheduling/appointments/Appointments.test.tsx
  src/__tests__/scheduling/appointments/appointment-slice.test.ts
  src/__tests__/scheduling/appointments/appointments-slice.test.ts
  src/__tests__/scheduling/appointments/edit/EditAppointment.test.tsx
  src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
  src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
  src/__tests__/scheduling/hooks/useAppointment.test.tsx
  src/__tests__/scheduling/hooks/useAppointments.test.tsx
  src/__tests__/scheduling/hooks/useDeleteAppointment.test.tsx
  src/__tests__/scheduling/hooks/useScheduleAppointment.test.tsx
  src/__tests__/scheduling/hooks/useUpdateAppointment.test.tsx
  src/scheduling/appointments/ViewAppointments.tsx
  src/scheduling/appointments/appointment-slice.ts
  src/scheduling/appointments/appointments-slice.ts
  src/scheduling/appointments/edit/EditAppointment.tsx
  src/scheduling/appointments/new/NewAppointment.tsx
  src/scheduling/appointments/util/scheduling-appointment.util.ts
  src/scheduling/appointments/util/validate-appointment.ts
  src/scheduling/appointments/view/ViewAppointment.tsx
  src/scheduling/hooks/useAppointment.tsx
  src/scheduling/hooks/useAppointments.tsx
  src/scheduling/hooks/useDeleteAppointment.tsx
  src/scheduling/hooks/useScheduleAppointment.tsx
  src/scheduling/hooks/useUpdateAppointment.tsx
  src/shared/locales/enUs/translations/scheduling/index.ts
  src/shared/store/index.ts
Labels: hacktoberfest-accepted, in progress

#2444 fix: resolve TitleProvider warnings logged in the browser console
  src/dashboard/Dashboard.tsx
  src/imagings/requests/NewImagingRequest.tsx
  src/imagings/search/ViewImagings.tsx
  src/incidents/list/ViewIncidents.tsx
  src/incidents/report/ReportIncident.tsx
  src/incidents/visualize/VisualizeIncidents.tsx
  src/labs/ViewLabs.tsx
  src/labs/requests/NewLabRequest.tsx
  src/medications/requests/NewMedicationRequest.tsx
  src/medications/search/ViewMedications.tsx
  src/patients/new/NewPatient.tsx
  src/patients/search/ViewPatients.tsx
  src/scheduling/appointments/ViewAppointments.tsx
  src/settings/Settings.tsx
Labels: hacktoberfest-accepted, in progress

#2448 fix(allergy): allergy data now gets refresh
  src/patients/view/ImportantPatientInfo.tsx
Labels: hacktoberfest-accepted, patients, 🐛bug

#2457 fix(patientview): add visit button height fix
  src/patients/view/ImportantPatientInfo.tsx
Labels: hacktoberfest-accepted, in progress, patients

#2447 refactor(patients): Improve date format consistency
  src/__tests__/shared/utils/formatDate.test.ts
  src/patients/search/ViewPatientsTable.tsx
  src/patients/view/ImportantPatientInfo.tsx
  src/shared/util/formatDate.ts
Labels: hacktoberfest-accepted, patients, 🚀enhancement

#2461 feat(patients): add medications tab
  src/__tests__/patients/hooks/usePatientMedications.test.tsx
  src/__tests__/patients/medications/Medications.test.tsx
  src/__tests__/patients/medications/MedicationsList.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/patients/hooks/usePatientMedications.tsx
  src/patients/medications/Medications.tsx
  src/patients/medications/MedicationsList.tsx
  src/patients/view/ViewPatient.tsx
  src/shared/db/PatientRepository.ts
  src/shared/locales/ar/translations/index.ts
  src/shared/locales/ar/translations/medications/index.ts
  src/shared/locales/ar/translations/patient/index.ts
  src/shared/locales/de/translations/index.ts
  src/shared/locales/de/translations/medications/index.ts
  src/shared/locales/de/translations/patient/index.ts
  src/shared/locales/enUs/translations/patient/index.ts
  src/shared/locales/es/translations/index.ts
  src/shared/locales/es/translations/medications/index.ts
  src/shared/locales/es/translations/patient/index.ts
  src/shared/locales/fr/translations/index.ts
  src/shared/locales/fr/translations/medications/index.ts
  src/shared/locales/fr/translations/patient/index.ts
  src/shared/locales/id/translations/index.ts
  src/shared/locales/id/translations/medications/index.ts
  src/shared/locales/id/translations/patient/index.ts
  src/shared/locales/it/translations/index.ts
  src/shared/locales/it/translations/medications/index.ts
  src/shared/locales/it/translations/patient/index.ts
  src/shared/locales/ja/translations/index.ts
  src/shared/locales/ja/translations/medications/index.ts
  src/shared/locales/ja/translations/patient/index.ts
  src/shared/locales/ptBr/translations/index.ts
  src/shared/locales/ptBr/translations/medications/index.ts
  src/shared/locales/ptBr/translations/patient/index.ts
  src/shared/locales/ru/translations/index.ts
  src/shared/locales/ru/translations/medications/index.ts
  src/shared/locales/ru/translations/patient/index.ts
  src/shared/locales/zhCN/translations/index.ts
  src/shared/locales/zhCN/translations/medications/index.ts
  src/shared/locales/zhCN/translations/patient/index.ts
Labels: hacktoberfest-accepted, in progress

#2452 fix(diagnoseform): show updated visit list
  src/patients/diagnoses/DiagnosisForm.tsx
Labels: hacktoberfest-accepted, in progress
