Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2020-09, with the labels that each got.

#2348 refactor(patient): refactor notes to use react query
  src/__tests__/patients/hooks/useAddPatientNote.test.ts
  src/__tests__/patients/hooks/usePatientNote.test.ts
  src/__tests__/patients/hooks/usePatientNotes.test.ts
  src/__tests__/patients/notes/NewNoteModal.test.tsx
  src/__tests__/patients/notes/NotesList.test.tsx
  src/__tests__/patients/notes/NotesTab.test.tsx
  src/__tests__/patients/notes/ViewNote.test.tsx
  src/patients/hooks/useAddPatientNote.ts
  src/patients/hooks/usePatientNote.ts
  src/patients/hooks/usePatientNotes.ts
  src/patients/notes/NewNoteModal.tsx
  src/patients/notes/NoteTab.tsx
  src/patients/notes/NotesList.tsx
  src/patients/notes/ViewNote.tsx
  src/patients/util/validate-note.ts
  src/patients/view/ViewPatient.tsx
Labels: in progress, 🚀enhancement

#2349 refactor(patient): refactor patient appointments to use react query
  src/__tests__/patients/appointments/AppointmentsList.test.tsx
  src/__tests__/patients/hooks/usePatientAppointments.test.tsx
  src/patients/appointments/AppointmentsList.tsx
  src/patients/hooks/usePatientAppointments.tsx
  src/scheduling/appointments/appointments-slice.ts
Labels: in progress, patients, 🚀enhancement

#2334 fix(navigation): align quick menu with sidebar and mobile version
  src/shared/components/navbar/Navbar.tsx
  src/shared/components/navbar/pageMap.tsx
Labels: in progress, 🚀enhancement

#2358 refactor(patient-labs): use react query instead of redux
  src/__tests__/patients/hooks/usePatientLabs.test.tsx
  src/__tests__/patients/labs/Labs.test.tsx
  src/__tests__/patients/labs/LabsList.test.tsx
  src/__tests__/patients/labs/LabsTab.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/patients/hooks/usePatientLabs.tsx
  src/patients/labs/Labs.tsx
  src/patients/labs/LabsList.tsx
  src/patients/labs/LabsTab.tsx
  src/patients/view/ViewPatient.tsx
Labels: labs, patients, 🚀enhancement

#2355 refactor(imaging): use react query instead of redux to fetch imaging data
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/imagings/hooks/useImagingRequest.test.tsx
  src/__tests__/imagings/hooks/useImagingSearch.test.tsx
  src/__tests__/imagings/hooks/useRequestImaging.test.tsx
  src/__tests__/imagings/imaging-slice.test.ts
  src/__tests__/imagings/imagings-slice.test.ts
  src/__tests__/imagings/requests/NewImagingRequest.test.tsx
  src/__tests__/imagings/search/ImagingRequestTable.test.tsx
  src/__tests__/imagings/search/ViewImagings.test.tsx
  src/__tests__/imagings/util/validate-imaging-request.test.ts
  src/imagings/Imagings.tsx
  src/imagings/ViewImagings.tsx
  src/imagings/hooks/useImagingRequest.tsx
  src/imagings/hooks/useImagingSearch.tsx
  src/imagings/hooks/useRequestImaging.tsx
  src/imagings/imaging-slice.ts
  src/imagings/imagings-slice.ts
  src/imagings/model/ImagingSearchRequest.ts
  src/imagings/requests/NewImagingRequest.tsx
  src/imagings/search/ImagingRequestTable.tsx
  src/imagings/search/ViewImagings.tsx
  src/imagings/util/validate-imaging-request.ts
  src/shared/store/index.ts
Labels: imaging, 🚀enhancement

#2311 feat(incidents): create downloadable incidents csv report
  package.json
  src/__tests__/incidents/list/ViewIncidentsTable.test.tsx
  src/__tests__/shared/utils/DataHelpers.test.ts
  src/incidents/list/ViewIncidentsTable.tsx
  src/shared/locales/enUs/translations/incidents/index.ts
  src/shared/util/DataHelpers.tsx
Labels: in progress, incidents, 🚀enhancement

#2360 feat(caregoal): add care goals to patient
  src/__tests__/patients/care-goals/AddCareGoalModal.test.tsx
  src/__tests__/patients/care-goals/CareGoalForm.test.tsx
  src/__tests__/patients/care-goals/CareGoalTab.test.tsx
  src/__tests__/patients/care-goals/CareGoalTable.test.tsx
  src/__tests__/patients/care-goals/ViewCareGoal.test.tsx
  src/__tests__/patients/care-goals/ViewCareGoals.test.tsx
  src/__tests__/patients/hooks/useAddCareGoal.test.tsx
  src/__tests__/patients/util/validate-caregoal.test.ts
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/patients/care-goals/AddCareGoalModal.tsx
  src/patients/care-goals/CareGoalForm.tsx
  src/patients/care-goals/CareGoalTab.tsx
  src/patients/care-goals/CareGoalTable.tsx
  src/patients/care-goals/ViewCareGoal.tsx
  src/patients/care-goals/ViewCareGoals.tsx
  src/patients/hooks/useAddCareGoal.tsx
  src/patients/hooks/useCareGoal.tsx
  src/patients/hooks/usePatientCareGoals.tsx
  src/patients/util/validate-caregoal.ts
  src/patients/view/ViewPatient.tsx
  src/shared/locales/enUs/translations/patient/index.ts
  src/shared/model/CareGoal.ts
  src/shared/model/Patient.ts
  src/shared/model/Permissions.ts
  src/user/user-slice.ts
Labels: patients, 🚀enhancement

#2383 chore: remove replit
  .replit
  README.md
Labels: dependencies, devops

#2381 chore(redux): remove unused redux code
  src/patients/hooks/useAddPatientNote.tsx
  src/patients/hooks/usePatientNote.tsx
  src/patients/hooks/usePatientNotes.tsx
  src/patients/patient-slice.ts
Labels: patients

#2376 fix(care plan): fix view button label in list
  src/patients/care-plans/CarePlanTable.tsx
Labels: 🐛bug

#2385 fix(labs): updates successfully completed message
  src/labs/ViewLab.tsx
  src/shared/locales/enUs/translations/labs/index.ts
Labels: in progress, labs

#2314 fix(shared): pouchdb auth popup
  couchdb/local.ini
  nginx.conf
  src/shared/config/pouchdb.ts
Labels: in progress, 🐛bug

#2389 refactor(medications): refactor medications search to use react query
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/medications/Medications.test.tsx
  src/__tests__/medications/ViewMedications.test.tsx
  src/__tests__/medications/hooks/useMedicationSearch.test.tsx
  src/__tests__/medications/medications-slice.test.ts
  src/__tests__/medications/search/MedicationRequestSearch.test.tsx
  src/__tests__/medications/search/MedicationRequestTable.test.tsx
  src/__tests__/medications/search/ViewMedications.test.tsx
  src/medications/Medications.tsx
  src/medications/ViewMedications.tsx
  src/medications/hooks/useMedicationSearch.tsx
  src/medications/medications-slice.ts
  src/medications/models/MedicationSearchRequest.ts
  src/medications/models/MedicationStatus.ts
  src/medications/search/MedicationRequestSearch.tsx
  src/medications/search/MedicationRequestTable.tsx
  src/medications/search/ViewMedications.tsx
  src/shared/db/MedicationRepository.ts
  src/shared/store/index.ts
Labels: medication

#2370 refactor(patient): refactor patient related persons to use react query
  src/__tests__/patients/hooks/useAddPatientRelatedPerson.test.tsx
  src/__tests__/patients/hooks/useRemovePatientRelatedPerson.test.tsx
  src/__tests__/patients/patient-slice.test.ts
  src/__tests__/patients/related-persons/AddRelatedPersonModal.test.tsx
  src/__tests__/patients/related-persons/RelatedPersonsTab.test.tsx
  src/patients/hooks/useAddPatientRelatedPerson.tsx
  src/patients/hooks/useRemovePatientRelatedPerson.tsx
  src/patients/patient-slice.ts
  src/patients/related-persons/AddRelatedPersonModal.tsx
  src/patients/related-persons/RelatedPersonTab.tsx
  src/patients/util/validate-related-person.ts
Labels: in progress

#2325 feat(labs): support list of notes for lab requests
  src/__tests__/labs/Labs.test.tsx
  src/__tests__/labs/ViewLab.test.tsx
  src/__tests__/labs/requests/NewLabRequest.test.tsx
  src/labs/ViewLab.tsx
  src/labs/requests/NewLabRequest.tsx
  src/shared/model/Lab.ts
Labels: in progress

#2393 refactor(patient): refactor patient visits to use react query
  src/__tests__/patients/hooks/useAddPatientVisit.test.tsx
  src/__tests__/patients/hooks/usePatientVisits.test.tsx
  src/__tests__/patients/hooks/useVisit.test.tsx
  src/__tests__/patients/util/validate-visit.test.ts
  src/__tests__/patients/visits/AddVisitModal.test.tsx
  src/__tests__/patients/visits/ViewVisit.test.tsx
  src/__tests__/patients/visits/VisitTab.test.tsx
  src/__tests__/patients/visits/VisitTable.test.tsx
  src/patients/hooks/useAddVisit.tsx
  src/patients/hooks/usePatientVisits.tsx
  src/patients/hooks/useVisit.tsx
  src/patients/patient-slice.ts
  src/patients/util/validate-visit.ts
  src/patients/view/ViewPatient.tsx
  src/patients/visits/AddVisitModal.tsx
  src/patients/visits/ViewVisit.tsx
  src/patients/visits/VisitForm.tsx
  src/patients/visits/VisitTab.tsx
  src/patients/visits/VisitTable.tsx
Labels: patients, 🚀enhancement

#2312 test(login): improve test login screen
  src/__tests__/login/Login.test.tsx
Labels: in progress

#2409 refactor(patient): refactor patient diagnoses
  src/__tests__/imagings/requests/NewImagingRequest.test.tsx
  src/__tests__/medications/search/MedicationRequestSearch.test.tsx
  src/__tests__/patients/diagnoses/AddDiagnosisModal.test.tsx
  src/__tests__/patients/diagnoses/Diagnoses.test.tsx
  src/__tests__/patients/diagnoses/DiagnosesList.test.tsx
  src/__tests__/patients/hooks/useAddPatientDiagnosis.test.tsx
  src/__tests__/patients/util/validate-diagnosis.test.ts
  src/__tests__/shared/components/input/SelectWithLabelFormGroup.test.tsx
  src/imagings/requests/NewImagingRequest.tsx
  src/incidents/list/ViewIncidents.tsx
  src/labs/ViewLabs.tsx
  src/medications/ViewMedication.tsx
  src/medications/requests/NewMedicationRequest.tsx
  src/medications/search/MedicationRequestSearch.tsx
  src/patients/ContactInfo.tsx
  src/patients/GeneralInformation.tsx
  src/patients/care-goals/CareGoalForm.tsx
  src/patients/care-plans/CarePlanForm.tsx
  src/patients/diagnoses/AddDiagnosisModal.tsx
  src/patients/diagnoses/Diagnoses.tsx
  src/patients/diagnoses/DiagnosesList.tsx
  src/patients/diagnoses/DiagnosisForm.tsx
  src/patients/hooks/useAddPatientDiagnosis.tsx
  src/patients/hooks/usePatientDiagnoses.tsx
  src/patients/util/validate-diagnosis.ts
  src/patients/visits/VisitForm.tsx
  src/scheduling/appointments/AppointmentDetailForm.tsx
  src/shared/components/input/LanguageSelector.tsx
  src/shared/components/input/SelectWithLabelFormGroup.tsx
  src/shared/components/input/index.tsx
Labels: in progress

#2408 feat: Added smooth scroll to index.css
  src/index.css
Labels: in progress

#2390 refactor(page-header): move title functionality to use a hooks
  src/App.tsx
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/imagings/Imagings.test.tsx
  src/__tests__/imagings/requests/NewImagingRequest.test.tsx
  src/__tests__/imagings/search/ViewImagings.test.tsx
  src/__tests__/incidents/Incidents.test.tsx
  src/__tests__/incidents/list/ViewIncidents.test.tsx
  src/__tests__/incidents/report/ReportIncident.test.tsx
  src/__tests__/incidents/view/ViewIncident.test.tsx
  src/__tests__/incidents/view/ViewIncidentDetails.test.tsx
  src/__tests__/labs/Labs.test.tsx
  src/__tests__/labs/ViewLab.test.tsx
  src/__tests__/labs/ViewLabs.test.tsx
  src/__tests__/labs/requests/NewLabRequest.test.tsx
  src/__tests__/medications/Medications.test.tsx
  src/__tests__/medications/ViewMedication.test.tsx
  src/__tests__/medications/requests/NewMedicationRequest.test.tsx
  src/__tests__/medications/search/ViewMedications.test.tsx
  src/__tests__/page-header/title/TitleProvider.test.tsx
  src/__tests__/page-header/title/title-slice.test.ts
  src/__tests__/page-header/title/useTitle.test.tsx
  src/__tests__/patients/Patients.test.tsx
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/new/NewPatient.test.tsx
  src/__tests__/patients/search/ViewPatients.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/__tests__/scheduling/appointments/Appointments.test.tsx
  src/__tests__/scheduling/appointments/ViewAppointments.test.tsx
  src/__tests__/scheduling/appointments/edit/EditAppointment.test.tsx
  src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
  src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
  src/__tests__/settings/Settings.test.tsx
  src/dashboard/Dashboard.tsx
  src/imagings/requests/NewImagingRequest.tsx
  src/imagings/search/ViewImagings.tsx
  src/incidents/list/ViewIncidents.tsx
  src/incidents/report/ReportIncident.tsx
  src/incidents/view/ViewIncident.tsx
  src/incidents/visualize/VisualizeIncidents.tsx
  src/labs/ViewLab.tsx
  src/labs/ViewLabs.tsx
  src/labs/requests/NewLabRequest.tsx
  src/medications/ViewMedication.tsx
  src/medications/requests/NewMedicationRequest.tsx
  src/medications/search/ViewMedications.tsx
  src/page-header/title/TitleContext.tsx
  src/page-header/title/title-slice.ts
  src/page-header/title/useTitle.tsx
  src/patients/edit/EditPatient.tsx
  src/patients/new/NewPatient.tsx
  src/patients/search/ViewPatients.tsx
  src/patients/view/ViewPatient.tsx
  src/scheduling/appointments/ViewAppointments.tsx
  src/scheduling/appointments/edit/EditAppointment.tsx
  src/scheduling/appointments/new/NewAppointment.tsx
  src/scheduling/appointments/view/ViewAppointment.tsx
  src/settings/Settings.tsx
  src/shared/store/index.ts
Labels: LOE - medium, in progress, 🚀enhancement

#2411 refactor(patients): use usePatient
  src/__tests__/patients/Patients.test.tsx
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/patient-slice.test.ts
  src/__tests__/patients/util/patient-util.test.ts
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/patients/appointments/AppointmentsList.tsx
  src/patients/edit/EditPatient.tsx
  src/patients/patient-slice.ts
  src/patients/util/patient-util.ts
  src/patients/util/set-patient-helper.ts
  src/patients/view/ViewPatient.tsx
Labels: in progress

#2410 refactor(labs): refactor labs module to use react query
  src/__tests__/labs/Labs.test.tsx
  src/__tests__/labs/ViewLab.test.tsx
  src/__tests__/labs/ViewLabs.test.tsx
  src/__tests__/labs/hooks/useCancelLab.test.ts
  src/__tests__/labs/hooks/useCompleteLab.test.ts
  src/__tests__/labs/hooks/useLab.test.ts
  src/__tests__/labs/hooks/useLabsSearch.test.ts
  src/__tests__/labs/hooks/useRequestLab.test.ts
  src/__tests__/labs/hooks/useUpdateLab.test.ts
  src/__tests__/labs/lab-slice.test.ts
  src/__tests__/labs/labs.slice.test.ts
  src/__tests__/labs/requests/NewLabRequest.test.tsx
  src/__tests__/labs/utils/validate-lab.test.ts
  src/__tests__/patients/care-goals/CareGoalTab.test.tsx
  src/__tests__/patients/care-plans/CarePlanTab.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/labs/ViewLab.tsx
  src/labs/ViewLabs.tsx
  src/labs/hooks/useCancelLab.ts
  src/labs/hooks/useCompleteLab.ts
  src/labs/hooks/useLab.ts
  src/labs/hooks/useLabsSearch.ts
  src/labs/hooks/useRequestLab.ts
  src/labs/hooks/useUpdateLab.ts
  src/labs/lab-slice.ts
  src/labs/labs-slice.ts
  src/labs/model/LabSearchRequest.ts
  src/labs/requests/NewLabRequest.tsx
  src/labs/utils/validate-lab.ts
  src/patients/hooks/usePatient.tsx
  src/shared/locales/enUs/translations/labs/index.ts
  src/shared/store/index.ts
Labels: in progress, labs, 🚀enhancement
