Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2020-02, with the labels that each got.

#1782 fix(frontend): update navbar component to match new format
  package.json
  src/__tests__/components/Navbar.test.tsx
  src/__tests__/scheduling/appointments-slice.test.ts
  src/components/Navbar.tsx
Labels: bug, dependencies

#1788 fix(patients): fix issue with patient duplicating on update
  .github/workflows/ci.yml
  src/clients/db/Repository.ts
  src/patients/related-persons/RelatedPersonTab.tsx
Labels: bug

#1805 Feature/view appointments calendar
  package.json
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/clients/db/AppointmentRepository.test.ts
  src/__tests__/scheduling/appointments/AppointmentDetailForm.test.tsx
  src/__tests__/scheduling/appointments/Appointments.test.tsx
  src/__tests__/scheduling/appointments/appointment-slice.test.ts
  src/__tests__/scheduling/appointments/appointments-slice.test.ts
  src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
  src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
  src/locales/en-US/translation.json
  src/scheduling/appointments/AppointmentDetailForm.tsx
  src/scheduling/appointments/Appointments.tsx
  src/scheduling/appointments/appointment-slice.ts
  src/scheduling/appointments/appointments-slice.ts
  src/scheduling/appointments/new/NewAppointment.tsx
  src/scheduling/appointments/view/ViewAppointment.tsx
  src/store/index.ts
Labels: enhancement, scheduling

#1811 fix(patients): makes patient search case insensitive
  src/__tests__/clients/db/PatientRepository.test.ts
  src/clients/db/PatientRepository.ts
Labels: bug, patients

#1780 fix(build): fix precommit lint hook issue
  .eslintrc.js
  .prettierrc
  package.json
  src/components/Navbar.tsx
Labels: bug, ci/cd

#1792 feat(navigation): navigate to patients profile on related person click
  src/__tests__/patients/related-persons/RelatedPersons.test.tsx
  src/patients/list/Patients.tsx
  src/patients/related-persons/RelatedPersonTab.tsx
Labels: enhancement, patients

#1819 test(tests): improve coverage, fix issues and errors in tests, cleanup
  src/__mocks__/i18next.js
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/page-header/useTitle.test.tsx
  src/__tests__/patients/GeneralInformation.test.tsx
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/new/NewPatient.test.tsx
  src/__tests__/patients/patient-slice.test.ts
  src/__tests__/patients/patients-slice.test.ts
  src/__tests__/patients/related-persons/RelatedPersons.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/__tests__/scheduling/appointments/Appointments.test.tsx
  src/__tests__/scheduling/appointments/appointment-slice.test.ts
  src/__tests__/scheduling/appointments/appointments-slice.test.ts
  src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
  src/patients/GeneralInformation.tsx
  src/patients/patient-slice.ts
  src/patients/patients-slice.ts
  src/patients/view/ViewPatient.tsx
  src/scheduling/appointments/appointment-slice.ts
  src/scheduling/appointments/appointments-slice.ts
Labels: in progress

#1816 feat(env): adds hospitalrun server information
  .env.example
  README.md
  src/config/pouchdb.ts
Labels: ci/cd, docs, enhancement, in progress

#1822 fix(patient-slice.ts): conditionally render family name and suffix
  src/__tests__/patients/patient-slice.test.ts
  src/patients/patient-slice.ts
Labels: in progress

#1810 fix(patients): stop "Loading..." when patient has no related persons
  src/__tests__/patients/related-persons/RelatedPersons.test.tsx
  src/locales/en-US/translation.json
  src/patients/related-persons/RelatedPersonTab.tsx
Labels: bug, in progress, patients

#1835 fix(test): fix failing windows tests
  src/__tests__/clients/db/PatientRepository.test.ts
  src/__tests__/patients/list/Patients.test.tsx
  src/__tests__/patients/new/NewPatient.test.tsx
  src/__tests__/patients/patient-slice.test.ts
Labels: bug

#1826 feat(view patient): add 'edit' icon to Edit button
  src/patients/view/ViewPatient.tsx
Labels: in progress, v2.x

#1817 feat(toolbar): basic button toolbar
  src/HospitalRun.tsx
  src/__tests__/page-header/ButtonBarProvider.test.tsx
  src/__tests__/page-header/ButtonToolBar.test.tsx
  src/__tests__/patients/list/Patients.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/__tests__/scheduling/appointments/Appointments.test.tsx
  src/page-header/ButtonBarProvider.tsx
  src/page-header/ButtonToolBar.tsx
  src/patients/list/Patients.tsx
  src/patients/view/ViewPatient.tsx
  src/scheduling/appointments/Appointments.tsx
Labels: enhancement, in progress, v2.x

#1815 feat(breadcrumb): add a breadcrumb underneath the page header
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/breadcrumbs/Breadcrumbs.test.tsx
  src/__tests__/breadcrumbs/breadcrumbs-slice.test.ts
  src/__tests__/breadcrumbs/useAddBreadcrumbs.test.tsx
  src/breadcrumbs/Breadcrumbs.tsx
  src/breadcrumbs/breadcrumbs-slice.ts
  src/breadcrumbs/useAddBreadcrumbs.ts
  src/index.css
  src/model/Breadcrumb.ts
  src/patients/appointments/AppointmentsList.tsx
  src/patients/edit/EditPatient.tsx
  src/patients/list/Patients.tsx
  src/patients/new/NewPatient.tsx
  src/patients/related-persons/RelatedPersonTab.tsx
  src/patients/view/ViewPatient.tsx
  src/scheduling/appointments/Appointments.tsx
  src/scheduling/appointments/new/NewAppointment.tsx
  src/scheduling/appointments/view/ViewAppointment.tsx
  src/store/index.ts
Labels: enhancement, in progress, v2.x

#1847 feat(delete appointment): adds ability to delete appointment
  src/__tests__/scheduling/appointments/appointment-slice.test.ts
  src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
  src/locales/en-US/translation.json
  src/model/Permissions.ts
  src/scheduling/appointments/appointment-slice.ts
  src/scheduling/appointments/view/ViewAppointment.tsx
  src/user/user-slice.ts
Labels: enhancement, scheduling

#1848 feat(allergies): adds ability to add allergy to appointment
  .github/workflows/ci.yml
  src/__tests__/patients/allergies/Allergies.test.tsx
  src/__tests__/patients/allergies/NewAllergyModal.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/locales/en-US/translation.json
  src/model/Allergy.ts
  src/model/Patient.ts
  src/model/Permissions.ts
  src/patients/allergies/Allergies.tsx
  src/patients/allergies/NewAllergyModal.tsx
  src/patients/util/timestamp-id-generator.ts
  src/patients/view/ViewPatient.tsx
  src/user/user-slice.ts
Labels: enhancement, patients

#1845 feat(edit appointment): implement Edit Appointment
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/clients/db/AppointmentRepository.test.ts
  src/__tests__/components/Navbar.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/__tests__/scheduling/appointments/AppointmentDetailForm.test.tsx
  src/__tests__/scheduling/appointments/Appointments.test.tsx
  src/__tests__/scheduling/appointments/appointment-slice.test.ts
  src/__tests__/scheduling/appointments/appointments-slice.test.ts
  src/__tests__/scheduling/appointments/edit/EditAppointment.test.tsx
  src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
  src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
  src/clients/db/AppointmentRepository.ts
  src/components/Navbar.tsx
  src/locales/en-US/translation.json
  src/patients/edit/EditPatient.tsx
  src/patients/new/NewPatient.tsx
  src/patients/view/ViewPatient.tsx
  src/scheduling/appointments/AppointmentDetailForm.tsx
  src/scheduling/appointments/Appointments.tsx
  src/scheduling/appointments/appointment-slice.ts
  src/scheduling/appointments/appointments-slice.ts
  src/scheduling/appointments/edit/EditAppointment.tsx
  src/scheduling/appointments/new/NewAppointment.tsx
  src/scheduling/appointments/view/ViewAppointment.tsx
Labels: enhancement, scheduling

#1849 fix(newPatient): correct input types of email and phone fields
  src/components/input/TextInputWithLabelFormGroup.tsx
  src/patients/GeneralInformation.tsx
Labels: in progress

#1864 docs(readme): Add slack CTA
  README.md
Labels: docs

#1868 fix(breadcrumb): set appointment date precision to minutes in breadcrumb
  src/__tests__/scheduling/appointments/util/scheduling-appointment.util.test.ts
  src/scheduling/appointments/util/scheduling-appointment.util.ts
Labels: bug, scheduling

#1870 fix(button toolbar): align buttons to the right in the toolbar
  src/__tests__/page-header/ButtonToolBar.test.tsx
  src/index.css
  src/page-header/ButtonToolBar.tsx
Labels: in progress
