Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2020-07, with the labels that each got.

#2200 feat(i18n): update russian language
  src/shared/locales/ru/translations/actions/index.ts
  src/shared/locales/ru/translations/incidents/index.ts
  src/shared/locales/ru/translations/index.ts
  src/shared/locales/ru/translations/labs/index.ts
  src/shared/locales/ru/translations/network-status/index.ts
  src/shared/locales/ru/translations/patient/index.ts
  src/shared/locales/ru/translations/patients/index.ts
  src/shared/locales/ru/translations/scheduling/index.ts
  src/shared/locales/ru/translations/settings/index.ts
  src/shared/locales/ru/translations/sex/index.ts
  src/shared/locales/ru/translations/states/index.ts
Labels: in progress, localization

#2190 feat: Added blood type info to patient
  src/__tests__/patients/GeneralInformation.test.tsx
  src/patients/GeneralInformation.tsx
  src/shared/locales/enUs/translations/blood-type/index.ts
  src/shared/locales/enUs/translations/index.ts
  src/shared/locales/enUs/translations/patient/index.ts
  src/shared/model/Patient.ts
Labels: in progress

#2203 fix: update hardcoded text with i18n locales
  src/labs/ViewLabs.tsx
Labels: in progress

#2197 feat: add new useTranslator
  src/__tests__/shared/hooks/useTranslator.test.ts
  src/dashboard/Dashboard.tsx
  src/incidents/list/ViewIncidents.tsx
  src/incidents/report/ReportIncident.tsx
  src/incidents/view/ViewIncident.tsx
  src/labs/ViewLab.tsx
  src/labs/ViewLabs.tsx
  src/labs/requests/NewLabRequest.tsx
  src/page-header/breadcrumbs/Breadcrumbs.tsx
  src/patients/ContactInfo.tsx
  src/patients/GeneralInformation.tsx
  src/patients/allergies/Allergies.tsx
  src/patients/allergies/NewAllergyModal.tsx
  src/patients/appointments/AppointmentsList.tsx
  src/patients/care-plans/AddCarePlanModal.tsx
  src/patients/care-plans/CarePlanForm.tsx
  src/patients/care-plans/CarePlanTab.tsx
  src/patients/care-plans/CarePlanTable.tsx
  src/patients/diagnoses/AddDiagnosisModal.tsx
  src/patients/diagnoses/Diagnoses.tsx
  src/patients/edit/EditPatient.tsx
  src/patients/labs/LabsTab.tsx
  src/patients/list/ViewPatients.tsx
  src/patients/new/NewPatient.tsx
  src/patients/notes/NewNoteModal.tsx
  src/patients/notes/NoteTab.tsx
  src/patients/related-persons/AddRelatedPersonModal.tsx
  src/patients/related-persons/RelatedPersonTab.tsx
  src/patients/view/ViewPatient.tsx
  src/scheduling/appointments/AppointmentDetailForm.tsx
  src/scheduling/appointments/ViewAppointments.tsx
  src/scheduling/appointments/edit/EditAppointment.tsx
  src/scheduling/appointments/new/NewAppointment.tsx
  src/scheduling/appointments/view/ViewAppointment.tsx
  src/settings/Settings.tsx
  src/shared/components/PageComponent.tsx
  src/shared/components/Sidebar.tsx
  src/shared/components/input/LanguageSelector.tsx
  src/shared/components/navbar/Navbar.tsx
  src/shared/components/network-status/NetworkStatusMessage.tsx
  src/shared/hooks/useTranslator.ts
Labels: in progress

#2198 fix(login): improved login validation
  src/__tests__/user/user-slice.test.ts
  src/login/Login.tsx
  src/shared/locales/enUs/translations/index.ts
  src/shared/locales/enUs/translations/user/index.ts
  src/user/user-slice.ts
Labels: in progress

#2212 fix(bug) add the translation key for 'logout'
  src/shared/components/navbar/Navbar.tsx
  src/shared/locales/enUs/translations/actions/index.ts
Labels: 🐛bug

#2214 fix(patients): fixes related person search crashing if no DoB
  src/patients/related-persons/AddRelatedPersonModal.tsx
  src/shared/hooks/useTranslator.ts
Labels: patients, 🐛bug

#2219 fix: weird spacing issue in quick add icon
  src/shared/components/navbar/Navbar.tsx
Labels: in progress

#2220 feat(navbar): add icons to 'quick add' icon in navbar
  src/__tests__/shared/components/navbar/Navbar.test.tsx
  src/shared/components/navbar/Navbar.tsx
  src/shared/components/navbar/pageMap.tsx
Labels: in progress, 🚀enhancement

#2221 fix(login): enter key does not submit login form
  src/login/Login.tsx
Labels: in progress

#2217 feat(patient): put "Unknow" next to date of brith field
  src/patients/GeneralInformation.tsx
Labels: in progress, patients

#2222 feat(incidents): add ability to resolve incidents
  src/__tests__/incidents/incident-slice.test.ts
  src/__tests__/incidents/view/ViewIncident.test.tsx
  src/__tests__/shared/utils/extractUsername.test.ts
  src/incidents/IncidentFilter.ts
  src/incidents/incident-slice.ts
  src/incidents/list/ViewIncidents.tsx
  src/incidents/view/ViewIncident.tsx
  src/shared/locales/enUs/translations/incidents/index.ts
  src/shared/model/Incident.ts
  src/shared/model/Permissions.ts
  src/shared/util/extractUsername.ts
  src/user/user-slice.ts
Labels: incidents, 🚀enhancement

#2237 feat(Navbar): remove search from navbar
  src/__tests__/shared/components/navbar/Navbar.test.tsx
  src/shared/components/navbar/Navbar.tsx
Labels: 🚀enhancement

#2236 feat(navbar): display currently logged in user name
  src/__tests__/shared/components/navbar/Navbar.test.tsx
  src/shared/components/navbar/Navbar.tsx
  src/shared/locales/enUs/translations/user/index.ts
Labels: in progress, 🚀enhancement

#2227 chore(init): add curl command to create a new DB user in the docker-compose
  .github/CONTRIBUTING.md
  docker-compose.yml
Labels: in progress

#2252 fix: correct incident icon
  src/shared/components/Sidebar.tsx
Labels: 🐛bug

#2240 feat(new): warn about potential duplicate patient (#2187)
  src/__tests__/patients/new/DuplicateNewPatientModal.test.tsx
  src/__tests__/patients/new/NewPatient.test.tsx
  src/__tests__/patients/util/is-possible-duplicate-patient.test.ts
  src/patients/new/DuplicateNewPatientModal.tsx
  src/patients/new/NewPatient.tsx
  src/patients/util/is-possible-duplicate-patient.ts
  src/shared/locales/enUs/translations/patients/index.ts
Labels: in progress, patients, 🚀enhancement
