Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2020-08, with the labels that each got.

#2202 Bug: page refresh (hot reload) fix
  src/App.tsx
  src/__tests__/App.test.tsx
  src/index.tsx
  src/login/Login.tsx
Labels: in progress

#2268 fix: reset lab state when navigation from lab form
  src/labs/lab-slice.ts
  src/labs/requests/NewLabRequest.tsx
Labels: in progress

#2250 feat(imaging): create basic imaging module
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/imagings/Imagings.test.tsx
  src/__tests__/imagings/ViewImagings.test.tsx
  src/__tests__/imagings/imaging-slice.test.ts
  src/__tests__/imagings/imagings-slice.test.ts
  src/__tests__/imagings/requests/NewImagingRequest.test.tsx
  src/__tests__/shared/components/Sidebar.test.tsx
  src/__tests__/shared/components/navbar/Navbar.test.tsx
  src/__tests__/shared/db/ImagingRepository.test.ts
  src/imagings/Imagings.tsx
  src/imagings/ViewImagings.tsx
  src/imagings/imaging-slice.ts
  src/imagings/imagings-slice.ts
  src/imagings/requests/NewImagingRequest.tsx
  src/shared/components/Sidebar.tsx
  src/shared/components/navbar/Navbar.tsx
  src/shared/components/navbar/pageMap.tsx
  src/shared/config/pouchdb.ts
  src/shared/db/ImagingRepository.ts
  src/shared/locales/enUs/translations/imagings/index.ts
  src/shared/locales/enUs/translations/index.ts
  src/shared/model/Imaging.ts
  src/shared/model/Permissions.ts
  src/shared/store/index.ts
  src/user/user-slice.ts
Labels: in progress, 🚀enhancement

#2235 feat(patients): add no patients exist
  src/__tests__/patients/list/ViewPatients.test.tsx
  src/__tests__/patients/patients-slice.test.ts
  src/__tests__/patients/view/NoPatientsExist.test.tsx
  src/patients/list/ViewPatients.tsx
  src/patients/patients-slice.ts
  src/patients/view/NoPatientsExist.tsx
  src/shared/db/Repository.ts
  src/shared/locales/ar/translations/patients/index.ts
  src/shared/locales/de/translations/patients/index.ts
  src/shared/locales/enUs/translations/patients/index.ts
  src/shared/locales/fr/translations/patients/index.ts
  src/shared/locales/ru/translations/patients/index.ts
Labels: in progress, 🚀enhancement

#2251 feat(patients): add visit functionality
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/__tests__/patients/visits/AddVisitModal.test.tsx
  src/__tests__/patients/visits/ViewVisit.test.tsx
  src/__tests__/patients/visits/VisitForm.test.tsx
  src/__tests__/patients/visits/VisitTab.test.tsx
  src/__tests__/patients/visits/VisitTable.test.tsx
  src/__tests__/shared/components/Sidebar.test.tsx
  src/__tests__/shared/components/navbar/Navbar.test.tsx
  src/patients/patient-slice.ts
  src/patients/view/ViewPatient.tsx
  src/patients/visits/AddVisitModal.tsx
  src/patients/visits/ViewVisit.tsx
  src/patients/visits/VisitForm.tsx
  src/patients/visits/VisitTab.tsx
  src/patients/visits/VisitTable.tsx
  src/shared/components/navbar/pageMap.tsx
  src/shared/locales/enUs/translations/patient/index.ts
  src/shared/model/Patient.ts
  src/shared/model/Permissions.ts
  src/shared/model/Visit.ts
  src/user/user-slice.ts
Labels: in progress, 🚀enhancement

#2276 feat(diagnosis): adds new diagnosis fields
  src/__tests__/patients/care-plans/CarePlanForm.test.tsx
  src/__tests__/patients/diagnoses/AddDiagnosisModal.test.tsx
  src/__tests__/patients/diagnoses/DiagnosisForm.test.tsx
  src/__tests__/patients/patient-slice.test.ts
  src/patients/diagnoses/AddDiagnosisModal.tsx
  src/patients/diagnoses/DiagnosisForm.tsx
  src/patients/patient-slice.ts
  src/shared/locales/enUs/translations/patient/index.ts
  src/shared/model/Diagnosis.ts
Labels: patients

#2283 fix(patient): successfully updated message should show actual text
  src/shared/locales/enUs/translations/patients/index.ts
Labels: patients, 🐛bug

#2249 feat(medications): implement basic medication module
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/medications/Medications.test.tsx
  src/__tests__/medications/ViewMedication.test.tsx
  src/__tests__/medications/ViewMedications.test.tsx
  src/__tests__/medications/medication-slice.test.ts
  src/__tests__/medications/medications-slice.test.ts
  src/__tests__/medications/requests/NewMedicationRequest.test.tsx
  src/__tests__/shared/components/Sidebar.test.tsx
  src/__tests__/shared/components/navbar/Navbar.test.tsx
  src/medications/Medications.tsx
  src/medications/ViewMedication.tsx
  src/medications/ViewMedications.tsx
  src/medications/medication-slice.ts
  src/medications/medications-slice.ts
  src/medications/requests/NewMedicationRequest.tsx
  src/shared/components/Sidebar.tsx
  src/shared/components/navbar/Navbar.tsx
  src/shared/components/navbar/pageMap.tsx
  src/shared/config/pouchdb.ts
  src/shared/db/MedicationRepository.ts
  src/shared/locales/enUs/translations/index.ts
  src/shared/locales/enUs/translations/medications/index.ts
  src/shared/model/Medication.ts
  src/shared/model/Permissions.ts
  src/shared/store/index.ts
  src/user/user-slice.ts
Labels: in progress, 🚀enhancement

#2304 fix: bugs with incidents and searching
  src/incidents/hooks/useIncidents.tsx
  src/shared/db/Repository.ts
Labels: 🐛bug

#2303 fix: remove console.log from tests output
  src/__tests__/incidents/hooks/useReportIncident.test.tsx
  src/__tests__/incidents/report/ReportIncident.test.tsx
  src/__tests__/patients/allergies/NewAllergyModal.test.tsx
  src/__tests__/patients/hooks/useAddAllergy.test.tsx
  src/patients/patients-slice.ts
Labels: in progress

#2313 fix(navbar): removed duplicate Report Incident link from quick create menu
  src/shared/components/navbar/Navbar.tsx
Labels: 🐛bug

#2285 fix: react-hooks/exhaustive-deps warnings do not appear when running
  .eslintrc.js
  src/__tests__/shared/components/network-status/NetworkStatusMessage.test.tsx
Labels: in progress

#2318 fix(sidebar): sidebar test improvements
  src/__tests__/shared/components/Sidebar.test.tsx
  src/shared/components/Sidebar.tsx
Labels: in progress

#2321 feat(diagnosis): link diagnosis with visit
  src/__tests__/patients/diagnoses/DiagnosisForm.test.tsx
  src/patients/diagnoses/AddDiagnosisModal.tsx
  src/patients/diagnoses/DiagnosisForm.tsx
  src/shared/locales/enUs/translations/patient/index.ts
  src/shared/model/Diagnosis.ts
Labels: in progress
