Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2020-05, with the labels that each got.

#2030 feat(patient): add email and phone number validation
  .github/workflows/compressed-size.yml
  package.json
  src/__tests__/patients/GeneralInformation.test.tsx
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/patient-slice.test.ts
  src/locales/enUs/translations/patient/index.ts
  src/patients/GeneralInformation.tsx
  src/patients/patient-slice.ts
Labels: patients, 🚀enhancement

#2031 feat(patients): escape string in appointments search
  src/__tests__/clients/db/AppointmentRepository.test.ts
  src/clients/db/AppointmentRepository.ts
Labels: patients, 🚀enhancement

#2035 feat(i18n): add italian translation
  src/i18n.ts
  src/locales/it/translations/actions/index.ts
  src/locales/it/translations/dashboard/index.ts
  src/locales/it/translations/index.ts
  src/locales/it/translations/labs/index.ts
  src/locales/it/translations/patient/index.ts
  src/locales/it/translations/patients/index.ts
  src/locales/it/translations/scheduling/index.ts
  src/locales/it/translations/sex/index.ts
  src/locales/it/translations/states/index.ts
Labels: in progress, localization, 🚀enhancement

#2032 feat(patient): add input validation
  src/__tests__/patients/patient-slice.test.ts
  src/locales/enUs/translations/patient/index.ts
  src/patients/GeneralInformation.tsx
  src/patients/patient-slice.ts
Labels: in progress, patients, 🚀enhancement

#1987 feat(viewpatient): added labs tab to ViewPatient
  package.json
  src/__tests__/patients/labs/LabsTab.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
  src/clients/db/LabRepository.ts
  src/locales/enUs/translations/patient/index.ts
  src/patients/labs/LabsTab.tsx
  src/patients/view/ViewPatient.tsx
Labels: in progress, patients, 🚀enhancement

#2040 feat(labs): add lab code
  src/__tests__/clients/db/LabRepository.test.ts
  src/__tests__/labs/ViewLab.test.tsx
  src/__tests__/labs/ViewLabs.test.tsx
  src/__tests__/utils/generateCode.test.ts
  src/clients/db/LabRepository.ts
  src/clients/db/PatientRepository.ts
  src/labs/ViewLab.tsx
  src/labs/ViewLabs.tsx
  src/locales/ar/translations/labs/index.ts
  src/locales/de/translations/labs/index.ts
  src/locales/enUs/translations/labs/index.ts
  src/locales/es/translations/labs/index.ts
  src/locales/fr/translations/labs/index.ts
  src/locales/in/translations/labs/index.ts
  src/locales/ja/translations/labs/index.ts
  src/locales/ptBr/translations/labs/index.ts
  src/locales/ru/translations/labs/index.ts
  src/locales/zr/translations/labs/index.ts
  src/model/Lab.ts
  src/util/generateCode.ts
Labels: in progress, labs, 🚀enhancement

#2044 fix(viewpatients): call PatientRepository.findAll() only once
  src/__tests__/patients/list/ViewPatients.test.tsx
  src/patients/list/ViewPatients.tsx
Labels: patients, 🐛bug

#2051 refactor(appointment): Appointment slice redux refactor
  package.json
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/labs/ViewLab.test.tsx
  src/__tests__/labs/lab-slice.test.ts
  src/__tests__/patients/GeneralInformation.test.tsx
  src/__tests__/scheduling/appointments/AppointmentDetailForm.test.tsx
  src/__tests__/scheduling/appointments/Appointments.test.tsx
  src/__tests__/scheduling/appointments/ViewAppointments.test.tsx
  src/__tests__/scheduling/appointments/appointment-slice.test.ts
  src/__tests__/scheduling/appointments/edit/EditAppointment.test.tsx
  src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
  src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
  src/components/input/DateTimePickerWithLabelFormGroup.tsx
  src/labs/lab-slice.ts
  src/locales/enUs/translations/scheduling/index.ts
  src/locales/fr/translations/scheduling/index.ts
  src/locales/ptBr/translations/scheduling/index.ts
  src/patients/patient-slice.ts
  src/scheduling/appointments/AppointmentDetailForm.tsx
  src/scheduling/appointments/Appointments.tsx
  src/scheduling/appointments/ViewAppointments.tsx
  src/scheduling/appointments/appointment-slice.ts
  src/scheduling/appointments/edit/EditAppointment.tsx
  src/scheduling/appointments/new/NewAppointment.tsx
  src/scheduling/appointments/view/ViewAppointment.tsx
Labels: in progress, 🚀enhancement

#2033 feat(labs): ability to filter by status on labs screen
  .gitignore
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/clients/db/LabRepository.test.ts
  src/__tests__/labs/ViewLabs.test.tsx
  src/__tests__/labs/labs.slice.test.ts
  src/__tests__/patients/related-persons/RelatedPersons.test.tsx
  src/clients/db/LabRepository.ts
  src/clients/db/Repository.ts
  src/components/Sidebar.tsx
  src/labs/ViewLabs.tsx
  src/labs/labs-slice.ts
  src/locales/enUs/translations/labs/index.ts
  src/store/index.ts
Labels: in progress, labs, 🚀enhancement

#2056 fix(datetime): datetime pickers are bigger now
  src/index.css
  src/patients/GeneralInformation.tsx
Labels: in progress, 🚀enhancement

#2060 feat(datepicker): add year selector dropdown
  src/components/input/DatePickerWithLabelFormGroup.tsx
Labels: in progress

#2057 fix: styling the Navbar to make it Sticky
  src/index.css
Labels: 🚀enhancement

#2067 fix: standardized react router imports in tests and source code
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/components/Sidebar.test.tsx
  src/__tests__/labs/Labs.test.tsx
  src/__tests__/labs/ViewLab.test.tsx
  src/__tests__/labs/ViewLabs.test.tsx
  src/__tests__/patients/allergies/Allergies.test.tsx
  src/__tests__/patients/appointments/AppointmentsList.test.tsx
  src/__tests__/patients/diagnoses/Diagnoses.test.tsx
  src/__tests__/patients/labs/LabsTab.test.tsx
  src/__tests__/patients/notes/NotesTab.test.tsx
  src/__tests__/patients/related-persons/RelatedPersons.test.tsx
  src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
  src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
  src/breadcrumbs/Breadcrumbs.tsx
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/labs/Labs.tsx
  src/labs/ViewLab.tsx
  src/labs/ViewLabs.tsx
  src/labs/requests/NewLabRequest.tsx
  src/patients/Patients.tsx
  src/patients/appointments/AppointmentsList.tsx
  src/patients/labs/LabsTab.tsx
  src/patients/list/ViewPatients.tsx
  src/patients/new/NewPatient.tsx
  src/patients/related-persons/RelatedPersonTab.tsx
  src/scheduling/appointments/Appointments.tsx
  src/scheduling/appointments/ViewAppointments.tsx
  src/scheduling/appointments/new/NewAppointment.tsx
  src/scheduling/appointments/view/ViewAppointment.tsx
Labels: 🐛bug

#2041 feat(incidents): implements MVP for incidents module
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/components/Sidebar.test.tsx
  src/__tests__/incidents/Incidents.test.tsx
  src/__tests__/incidents/incident-slice.test.ts
  src/__tests__/incidents/incidents-slice.test.ts
  src/__tests__/incidents/list/ViewIncidents.test.tsx
  src/__tests__/incidents/report/ReportIncident.test.tsx
  src/__tests__/incidents/view/ViewIncident.test.tsx
  src/clients/db/IncidentRepository.ts
  src/components/Sidebar.tsx
  src/components/input/DateTimePickerWithLabelFormGroup.tsx
  src/config/pouchdb.ts
  src/incidents/Incidents.tsx
  src/incidents/incident-slice.ts
  src/incidents/incidents-slice.ts
  src/incidents/list/ViewIncidents.tsx
  src/incidents/report/ReportIncident.tsx
  src/incidents/view/ViewIncident.tsx
  src/locales/enUs/translations/incidents/index.ts
  src/locales/enUs/translations/index.ts
  src/model/Incident.ts
  src/model/Permissions.ts
  src/model/User.ts
  src/store/index.ts
  src/user/user-slice.ts
Labels: incidents, 🚀enhancement

#2075 fix: standardize mock store setup in tests
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/breadcrumbs/Breadcrumbs.test.tsx
  src/__tests__/breadcrumbs/useAddBreadcrumbs.test.tsx
  src/__tests__/components/Sidebar.test.tsx
  src/__tests__/incidents/Incidents.test.tsx
  src/__tests__/incidents/list/ViewIncidents.test.tsx
  src/__tests__/incidents/report/ReportIncident.test.tsx
  src/__tests__/incidents/view/ViewIncident.test.tsx
  src/__tests__/labs/Labs.test.tsx
  src/__tests__/labs/ViewLab.test.tsx
  src/__tests__/labs/ViewLabs.test.tsx
  src/__tests__/labs/requests/NewLabRequest.test.tsx
  src/__tests__/page-header/useTitle.test.tsx
  src/__tests__/patients/Patients.test.tsx
  src/__tests__/patients/allergies/Allergies.test.tsx
  src/__tests__/patients/allergies/NewAllergyModal.test.tsx
  src/__tests__/patients/appointments/AppointmentsList.test.tsx
  src/__tests__/patients/diagnoses/AddDiagnosisModal.test.tsx
  src/__tests__/patients/diagnoses/Diagnoses.test.tsx
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/labs/LabsTab.test.tsx
  src/__tests__/patients/new/NewPatient.test.tsx
  src/__tests__/patients/notes/NewNoteModal.test.tsx
  src/__tests__/patients/notes/NotesTab.test.tsx
  src/__tests__/patients/related-persons/AddRelatedPersonModal.test.tsx
  src/__tests__/patients/related-persons/RelatedPersons.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/__tests__/scheduling/appointments/Appointments.test.tsx
  src/__tests__/scheduling/appointments/ViewAppointments.test.tsx
  src/__tests__/scheduling/appointments/edit/EditAppointment.test.tsx
  src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
  src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
Labels: in progress, 🚀enhancement

#2085 fix(incidents): add loading during fetch phase
  src/incidents/view/ViewIncident.tsx
Labels: incidents, 🚀enhancement

#2087 feat(incidents): filter incidents
  src/__tests__/incidents/incidents-slice.test.ts
  src/__tests__/incidents/list/ViewIncidents.test.tsx
  src/clients/db/IncidentRepository.ts
  src/incidents/IncidentFilter.ts
  src/incidents/incidents-slice.ts
  src/incidents/list/ViewIncidents.tsx
  src/locales/enUs/translations/incidents/index.ts
Labels: incidents, 🚀enhancement

#2095 refactor(i18n): edit chinese and indonesian ISO 639-1 codes
  README.md
  src/i18n.ts
  src/locales/README.md
  src/locales/id/translations/actions/index.ts
  src/locales/id/translations/dashboard/index.ts
  src/locales/id/translations/index.ts
  src/locales/id/translations/labs/index.ts
  src/locales/id/translations/patient/index.ts
  src/locales/id/translations/patients/index.ts
  src/locales/zhCN/translations/actions/index.ts
  src/locales/zhCN/translations/dashboard/index.ts
  src/locales/zhCN/translations/index.ts
  src/locales/zhCN/translations/labs/index.ts
  src/locales/zhCN/translations/patient/index.ts
  src/locales/zhCN/translations/patients/index.ts
Labels: localization

#2097 feat(i18n): German Translation
  src/locales/de/translations/actions/index.ts
  src/locales/de/translations/dashboard/index.ts
  src/locales/de/translations/incidents/index.ts
  src/locales/de/translations/index.ts
  src/locales/de/translations/labs/index.ts
  src/locales/de/translations/patient/index.ts
  src/locales/de/translations/scheduling/index.ts
  src/locales/de/translations/sex/index.ts
  src/locales/de/translations/states/index.ts
Labels: in progress, localization

#2096 feat(settings): add navbar dropdown and settings page
  package.json
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/settings/Settings.test.tsx
  src/components/Navbar.tsx
  src/components/input/LanguageSelector.tsx
  src/i18n.ts
  src/locales/ar/translations/index.ts
  src/locales/ar/translations/settings/index.ts
  src/locales/de/translations/index.ts
  src/locales/de/translations/settings/index.ts
  src/locales/enUs/translations/index.ts
  src/locales/enUs/translations/settings/index.ts
  src/locales/es/translations/index.ts
  src/locales/es/translations/settings/index.ts
  src/locales/fr/translations/index.ts
  src/locales/fr/translations/settings/index.ts
  src/locales/id/translations/index.ts
  src/locales/id/translations/settings/index.ts
  src/locales/it/translations/index.ts
  src/locales/it/translations/settings/index.ts
  src/locales/ja/translations/index.ts
  src/locales/ja/translations/settings/index.ts
  src/locales/ptBr/translations/index.ts
  src/locales/ptBr/translations/settings/index.ts
  src/locales/ru/translations/index.ts
  src/locales/ru/translations/settings/index.ts
  src/locales/zhCN/translations/index.ts
  src/locales/zhCN/translations/settings/index.ts
  src/settings/Settings.tsx
Labels: in progress, user, 🚀enhancement

#2108 feat(navbar): add shortcut icon to the create pages
  src/__tests__/components/Navbar.test.tsx
  src/components/Navbar.tsx
Labels: 🚀enhancement
