Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2020-04, with the labels that each got.

#1955 feat(patients): new related person to add related person
  src/__tests__/patients/related-persons/AddRelatedPersonModal.test.tsx
  src/__tests__/patients/related-persons/RelatedPersons.test.tsx
  src/locales/enUs/translations/patient/index.ts
  src/patients/related-persons/AddRelatedPersonModal.tsx
  src/patients/related-persons/RelatedPersonTab.tsx
Labels: enhancement, patients

#1956 feat: Added new proposed links to the sidebar
  src/__tests__/components/Sidebar.test.tsx
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/locales/enUs/translations/patients/index.ts
  src/locales/enUs/translations/scheduling/index.ts
Labels: enhancement, in progress

#1961 feat(patients): add notes to patients
  .env.example
  src/__tests__/patients/notes/NewNoteModal.test.tsx
  src/__tests__/patients/notes/NotesTab.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/components/input/TextFieldWithLabelFormGroup.tsx
  src/locales/enUs/translations/patient/index.ts
  src/locales/enUs/translations/patients/index.ts
  src/model/Note.ts
  src/model/Patient.ts
  src/patients/notes/NewNoteModal.tsx
  src/patients/notes/NoteTab.tsx
  src/patients/view/ViewPatient.tsx
Labels: enhancement, patients

#1962 feat(labs): adds ability to add, view, and list lab requests
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/components/Navbar.test.tsx
  src/__tests__/components/Sidebar.test.tsx
  src/__tests__/labs/Labs.test.tsx
  src/__tests__/labs/ViewLab.test.tsx
  src/__tests__/labs/ViewLabs.test.tsx
  src/__tests__/labs/requests/NewLabRequest.test.tsx
  src/clients/db/LabRepository.ts
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/config/pouchdb.ts
  src/labs/Labs.tsx
  src/labs/ViewLab.tsx
  src/labs/ViewLabs.tsx
  src/labs/requests/NewLabRequest.tsx
  src/locales/enUs/translations/actions/index.ts
  src/locales/enUs/translations/index.ts
  src/locales/enUs/translations/labs/index.ts
  src/model/Lab.ts
  src/model/Permissions.ts
  src/user/user-slice.ts
Labels: enhancement, labs

#1965 feat(patients): refactor patient list to use table
  src/__tests__/patients/list/Patients.test.tsx
  src/locales/enUs/translations/patient/index.ts
  src/patients/list/Patients.tsx
Labels: patients, 🚀enhancement

#1968 feat(patients): adds ability to remove related person
  src/__tests__/patients/related-persons/RelatedPersons.test.tsx
  src/locales/enUs/translations/actions/index.ts
  src/patients/related-persons/RelatedPersonTab.tsx
Labels: patients, 🚀enhancement

#1959 fix(patients): current patient can no longer be related person
  src/__tests__/patients/related-persons/AddRelatedPersonModal.test.tsx
  src/patients/related-persons/AddRelatedPersonModal.tsx
Labels: in progress

#1977 fix(patient): Input validation and error feedback
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/new/NewPatient.test.tsx
  src/components/input/DatePickerWithLabelFormGroup.tsx
  src/locales/enUs/translations/patient/index.ts
  src/locales/ptBr/translations/patient/index.ts
  src/patients/GeneralInformation.tsx
  src/patients/edit/EditPatient.tsx
  src/patients/new/NewPatient.tsx
Labels: in progress

#1980 docs: updates documentation for better onboarding
  .github/CONTRIBUTING.md
  README.md
Labels: docs

#1986 ci(github): add expression syntax to allow lint step to fail
  .github/workflows/ci.yml
Labels: core-team

#1964 feat(patient): add appointment button
  src/__tests__/patients/appointments/AppointmentsList.test.tsx
  src/locales/enUs/translations/patient/index.ts
  src/patients/appointments/AppointmentsList.tsx
Labels: in progress, patients, 🚀enhancement

#1990 Sorting
  src/__tests__/scheduling/appointments/Appointments.test.tsx
  src/clients/Sort.ts
  src/clients/db/LabRepository.ts
  src/clients/db/Repository.ts
  src/clients/db/SortRequest.ts
Labels: 🚀enhancement

#1991 feat(patients): add feedback to add related person form
  src/__tests__/patients/related-persons/AddRelatedPersonModal.test.tsx
  src/locales/enUs/translations/patient/index.ts
  src/patients/related-persons/AddRelatedPersonModal.tsx
Labels: patients, 🚀enhancement

#1994 fix(patients): add translation for patient.Code
  src/locales/enUs/translations/patient/index.ts
Labels: patients, 🐛bug

#2002 feat(patients): set max date in date of birth date picker
  .env.example
  src/__tests__/components/input/DatePickerWithLabelFormGroup.test.tsx
  src/__tests__/patients/GeneralInformation.test.tsx
  src/components/input/DatePickerWithLabelFormGroup.tsx
  src/patients/GeneralInformation.tsx
Labels: patients, 🚀enhancement

#1995 feat(labs): use redux
  src/__tests__/labs/Labs.test.tsx
  src/__tests__/labs/ViewLab.test.tsx
  src/__tests__/labs/ViewLabs.test.tsx
  src/__tests__/labs/lab-slice.test.ts
  src/__tests__/labs/requests/NewLabRequest.test.tsx
  src/labs/ViewLab.tsx
  src/labs/lab-slice.ts
  src/labs/requests/NewLabRequest.tsx
  src/store/index.ts
Labels: labs, 🚀enhancement

#2003 feat(appointments) reason field no longer labelled as a required field when making appointments.
  src/__tests__/components/input/TextFieldWithLabelFormGroup.test.tsx
  src/components/input/TextFieldWithLabelFormGroup.tsx
Labels: scheduling, 🐛bug

#2010 fix(labs): Cleanup small issues with lab section
  src/locales/enUs/translations/labs/index.ts
Labels: labs, 🐛bug

#2013 feat(i18n): add French language
  src/i18n.ts
  src/locales/fr/translations/actions/index.ts
  src/locales/fr/translations/dashboard/index.ts
  src/locales/fr/translations/index.ts
  src/locales/fr/translations/labs/index.ts
  src/locales/fr/translations/patient/index.ts
  src/locales/fr/translations/patients/index.ts
  src/locales/fr/translations/scheduling/index.ts
  src/locales/fr/translations/sex/index.ts
  src/locales/fr/translations/states/index.ts
Labels: in progress, localization

#2015 ci(gitpod): enhance gitpod setup.
  .github/CONTRIBUTING.md
  .gitpod.yml
  README.md
Labels: ci/cd, docs

#2018 feat(localization): add portuguese language
  src/locales/ptBr/translations/actions/index.ts
  src/locales/ptBr/translations/index.ts
  src/locales/ptBr/translations/labs/index.ts
  src/locales/ptBr/translations/patient/index.ts
  src/locales/ptBr/translations/patients/index.ts
  src/locales/ptBr/translations/scheduling/index.ts
Labels: 🚀enhancement

#2017 feat: refactors patients module to use redux
  package.json
  src/HospitalRun.tsx
  src/__tests__/HospitalRun.test.tsx
  src/__tests__/patients/GeneralInformation.test.tsx
  src/__tests__/patients/Patients.test.tsx
  src/__tests__/patients/allergies/Allergies.test.tsx
  src/__tests__/patients/allergies/NewAllergyModal.test.tsx
  src/__tests__/patients/diagnoses/AddDiagnosisModal.test.tsx
  src/__tests__/patients/diagnoses/Diagnoses.test.tsx
  src/__tests__/patients/edit/EditPatient.test.tsx
  src/__tests__/patients/list/ViewPatients.test.tsx
  src/__tests__/patients/new/NewPatient.test.tsx
  src/__tests__/patients/notes/NewNoteModal.test.tsx
  src/__tests__/patients/notes/NotesTab.test.tsx
  src/__tests__/patients/patient-slice.test.ts
  src/__tests__/patients/related-persons/AddRelatedPersonModal.test.tsx
  src/__tests__/patients/related-persons/RelatedPersons.test.tsx
  src/locales/enUs/translations/patient/index.ts
  src/model/Note.ts
  src/model/RelatedPerson.ts
  src/patients/GeneralInformation.tsx
  src/patients/Patients.tsx
  src/patients/allergies/Allergies.tsx
  src/patients/allergies/NewAllergyModal.tsx
  src/patients/diagnoses/AddDiagnosisModal.tsx
  src/patients/diagnoses/Diagnoses.tsx
  src/patients/edit/EditPatient.tsx
  src/patients/list/ViewPatients.tsx
  src/patients/new/NewPatient.tsx
  src/patients/notes/NewNoteModal.tsx
  src/patients/notes/NoteTab.tsx
  src/patients/patient-slice.ts
  src/patients/related-persons/AddRelatedPersonModal.tsx
  src/patients/related-persons/RelatedPersonTab.tsx
  src/patients/view/ViewPatient.tsx
  src/util/uuid.ts
Labels: patients, 🚀enhancement

#2012 fix(patients): fixes search when using special characters
  package.json
  src/__tests__/clients/db/PatientRepository.test.ts
  src/clients/db/PatientRepository.ts
  src/components/Sidebar.tsx
Labels: in progress
