Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2020-11, with the labels that each got.

#2465 fix(i18n): fixed typo of remission text
  src/shared/model/Diagnosis.ts
Labels: hacktoberfest-accepted, in progress

#2455 fix(incidents): running Incidents.test.tsx
  package.json
  src/setupTests.js
Labels: ci/cd, hacktoberfest-accepted, in progress, 🐛bug

#2458 fix(patient): allergy list style
  src/__tests__/patients/view/ImportantPatientInfo.test.tsx
  src/patients/view/ImportantPatientInfo.tsx
Labels: hacktoberfest-accepted, in progress, patients, 🚀enhancement

#2456 fix(i18n): add diagnosis translations
  src/shared/locales/de/translations/patient/index.ts
  src/shared/locales/enUs/translations/patient/index.ts
  src/shared/locales/fr/translations/patient/index.ts
  src/shared/locales/it/translations/patient/index.ts
  src/shared/locales/ru/translations/patient/index.ts
Labels: hacktoberfest-accepted, in progress

#2469 feat: auto populate patients
  src/__tests__/patients/appointments/AppointmentsList.test.tsx
  src/__tests__/patients/view/ViewPatient.test.tsx
  src/patients/appointments/AppointmentsList.tsx
  src/patients/view/ViewPatient.tsx
  src/scheduling/appointments/new/NewAppointment.tsx
Labels: hacktoberfest-accepted, in progress

#2471 refactor(patient): decouple patient validator from redux code
  src/__tests__/patients/util/validate-patient.test.ts
  src/patients/patient-slice.ts
  src/patients/util/validate-patient.ts
Labels: in progress
