Repository HospitalRun/hospitalrun-frontend, pull requests merged in 2021-01, with the labels that each got.

#2538 fix(mobile navbar): remove invalid links
  src/shared/components/navbar/pageMap.tsx
Labels: LOE - small, in progress, 🐛bug

#2542 docs(contributing) - fix cleanup scripts reference
  .github/CONTRIBUTING.md
Labels: docs

#2532 feat(incident): added optional patient field in report incident
  src/__tests__/incidents/report/ReportIncident.test.tsx
  src/incidents/report/ReportIncident.tsx
  src/incidents/view/ViewIncidentDetails.tsx
  src/shared/locales/de/translations/incidents/index.ts
  src/shared/locales/enUs/translations/incidents/index.ts
  src/shared/locales/ru/translations/incidents/index.ts
  src/shared/model/Incident.ts
Labels: LOE - medium, incidents, 🚀enhancement

#2544 fix(ImagingRequest): imaging table requestedBy show current usr
  package.json
  src/__tests__/imagings/hooks/useRequestImaging.test.tsx
  src/__tests__/imagings/requests/NewImagingRequest.test.tsx
  src/imagings/hooks/useRequestImaging.tsx
  src/imagings/requests/NewImagingRequest.tsx
  src/imagings/search/ImagingRequestTable.tsx
  src/shared/model/Imaging.ts
  src/user/user-slice.ts
Labels: in progress

#2552 fix(lab): In New lab request make the visit field required
  src/__tests__/labs/requests/NewLabRequest.test.tsx
  src/labs/requests/NewLabRequest.tsx
Labels: LOE - small, in progress, labs, 🐛bug
